version: "3.3"

services:
  testdb:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db:/var/lib/postgresql/data

  testcms:
    build: .
    ports:
      - "8889:8889"
      - "8888:8888"
    depends_on:
      - "testdb"
    environment:
      CMS_CONFIG: /usr/local/etc/cms-testdb.conf
      # Could be removed in the future, see:
      # - https://github.com/pytest-dev/pytest/issues/7443
      # - https://github.com/actions/runner/issues/241
      PYTEST_ADDOPTS: --color=yes
    volumes:
      - "./codecov:/home/cmsuser/cms/codecov"
    privileged: true
    command: >
      wait-for-it testdb:5432 -- sh -c "
      cmsLogService &
      echo "1" | cmsResourceService -a ;
      wait ;
      "
      #createdb --host=testdb --username=postgres cmsdbfortesting ;
      #cmsInitDB ;
      #cmsAddAdmin markus ;
      #dropdb --host=testdb --username=postgres cmsdbfortesting ;
      #cmsAdminWebServer ;
